[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = 'default-src * data: blob: unsafe-inline unsafe-eval; script-src * data: blob: unsafe-inline unsafe-eval; style-src * data: blob: unsafe-inline; img-src * data: blob: https:; font-src * data: blob:; connect-src * data: blob: ws: wss:'
